from math import isnan
from typing import Optional
from rapidfuzz import fuzz
import re
from copy import deepcopy
from .DynamicDeterministicExtractor import DynamicDeterministicExtractor
from core.llm import OllamaContentExtractor


class ExtractContentModel:
    def __init__(self, metadata_templates: list, similarity: float = 70, similarity_clean: float = 85) -> None:
        # Content generated by GEMINI
        self.templates = metadata_templates
        self.similarity = similarity
        self.similarity_clean = similarity_clean
        

    async def content_extract(self, template: str, content: list[str]) -> tuple[dict, dict]:
        # Content extraction preparation phase

        results = {
            "step_1": 0,
            "step_2": 0,
            "step_3": 0,
            "last_step": "NONE",
            "total_analyzed": len(content)
        }

        parameters = {}
        metadata = next((item for item in self.templates if item["template_text"] == template), None)

        if metadata == None:
            results['total_analyzed'] = 0
            return parameters, results

        len_parameters = len(metadata['variable_blocks'])

        if len_parameters == 0:
            results['total_analyzed'] = 0
            return parameters, results

        for i in metadata['variable_blocks']:
            idx = i['position']
            parameters[idx] = {
                "type_parameter": i['inferred_type'],
                "index": idx,
                "values": []
            }


        # 1. Check whether each piece of content matches any template type already recognized by GEMINI
        # Strategy: Text Comparisons
        content_templates, fails = self._similary_templates(content)

        new_parameters = []
        for key, item in content_templates.items():
            for block in item['variable_blocks']:
                for template_main in parameters.values():
                    if template_main['type_parameter'] == block['inferred_type']:
                        value = self._extract_placeholder(item['template_text'], key, block['position'])
                        value2 = self._extract_placeholder_by_spaces(item['template_text'], key, block['position'])
                        if value and len(value) != 1:
                            new_parameters.append((template_main['index'], value))
                        if not value and value2:
                            new_parameters.append((template_main['index'], value2))
                        

        for key, value in new_parameters:
            parameters[key]['values'].append(value)
            results['step_1'] += 1

        if len(fails) == 0 and results["last_step"] == "NONE":
            results["last_step"] = "STEP_1"
            
        # 2. If GEMINI cannot identify it, use a deterministic model to check whether the remaining content has parameters that need to be filled in
        deterministic_model = DynamicDeterministicExtractor(metadata, False)

        solved = []
        for item_fail in fails:
            if isinstance(item_fail, float) and isnan(item_fail):
                response = {}
            else:
                response = deterministic_model.process(str(item_fail))
            # WARN : If just one item of any kind is extracted at 60%, it is marked as resolved
            # There may be other parameters in the template that can be extracted
            for key, items in response.items():
                for item in items:
                    # if item.status == "extracted" and item.confidence >= 60:
                    if item.confidence >= 60:
                        parameters[key]['values'].append(item.value)
                        if item not in solved:
                            solved.append(item_fail)

        solved = list(set(solved))
        for item in solved:
            fails.remove(item)
            results["step_2"] += 1


        if len(fails) == 0 and results["last_step"] == "NONE":
            results["last_step"] = "STEP_2"

        # 3. Use Ollama to extract the content as a last resort, in case the deterministic method fails to identify anything or has invalid parameters
        solved = []
        if len(fails) != 0:
            results["last_step"] = "STEP_3"
            model_ollama = OllamaContentExtractor()
            response = await model_ollama.parse_logs(fails, metadata)

            # WARN : It only takes one non-empty item of any type to be marked as resolved
            for item, values in response.items():
                if not values:
                    continue
                for key in values.keys():
                    if values[key] == None or len(values[key]) == 0:
                        continue

                    index = None

                    # Search index by type_parameter
                    for param in parameters.values():
                        if param["type_parameter"] == key:
                            index = param["index"]
                            break

                    if not index or index not in parameters:
                        continue

                    try:
                        parameters[index]['values'].extend(values[key])
                        solved.append(item)
                    except ValueError:
                        continue

        solved = list(set(solved))
        for item in solved:
            fails.remove(item)
            results["step_3"] += 1

        parameters = self._clean_parameters_alfanumeric(parameters, metadata)

        # Clean duplicate itens in parameters
        for item in parameters.values():
            item['values'] = list(set(item['values']))

        return parameters, results


    # INFO: Simply using fuzz to find similar sentences, using SentenceTransformer slows down the process, since it is a context model that must be loaded for each request
    def _similary_templates(self, content: list[Optional[str]] | list[str]) -> tuple:
        content_templates = {}

        fails = []
        for item in content:
            if item == None:
                continue
            prob = self.similarity
            target_item = None
            
            for template in self.templates:
                target_prob = fuzz.ratio(item, template['template_text'])
                if target_prob >= prob:
                    target_item = template
                    prob = target_prob

            if target_item is not None:
                content_templates[item] = target_item
            else:
                fails.append(item)

        return content_templates, fails


    def _extract_placeholder(self, template: str, texto: str, index: int) -> str | None:
        especiais = r".^$*+?{}[]\|()"
        
        pattern = ""
        i = 0
        while i < len(template):
            if template[i:i+3] == "<*>":
                pattern += "(.+?)"
                i += 3
            elif template[i] in especiais:
                pattern += "\\" + template[i]
                i += 1
            elif template[i] == " ":
                pattern += r"\s+"
                i += 1
            else:
                pattern += template[i]
                i += 1

        match = re.search(pattern, texto)
        if match and match.lastindex and index <= match.lastindex:
            return match.group(index)
        return None


    def _extract_placeholder_by_spaces(self, template: str, texto: str, index: int) -> str | None:
        template_parts = template.split()
        texto_parts = texto.split()

        placeholder_positions = [
            i for i, part in enumerate(template_parts) if part == "<*>"
        ]

        if index - 1 >= len(placeholder_positions):
            return None

        pos = placeholder_positions[index - 1]

        if pos >= len(texto_parts):
            return None

        return texto_parts[pos]


    def _clean_parameters_alfanumeric(self, content: dict, template_target: dict) -> dict:
        patterns = [
            r"\b[A-Z]{2,5}[._]?\d+(?:[.,_]\d+){1,}\b",
            r"\b[A-Z]{2,5}(?:[._][A-Z0-9]+){2,}\b",
        ]

        regex = re.compile("|".join(f"({p})" for p in patterns), re.IGNORECASE)

        copy_content = deepcopy(content)

        for block in template_target["variable_blocks"]:
            example = block["examples"][0]
            if regex.search(example):
                letras_match = re.match(r"^([A-Za-z]+)(?:\.|\d)", example)

                if letras_match:
                    letras = letras_match.group(1)
                else:
                    continue

                for value in content[block["position"]]["values"]:
                    if not value.startswith(letras):
                        copy_content[block["position"]]["values"].remove(value)

            # Cases involving only numbers
            if re.fullmatch(r"^\d+$", example):
                for value in content[block["position"]]["values"]:
                    if not re.fullmatch(r"^\d+$", value):
                        copy_content[block["position"]]["values"].remove(value)

        return copy_content
